boss.name0="Nergigante"
boss.hp0=100
boss.atk0=20
boss.def0=0
boss.vel0=50
boss.sprite0="/org/example/ProgettoUIDFinal/images/bossSprite.png"
boss.bg0="/org/example/ProgettoUIDFinal/imagini/Boss/BossBackground0.jpg"

boss.name1="Mago"
boss.hp1=250
boss.atk1=30
boss.def1=25
boss.vel1=60
boss.sprite1="/org/example/ProgettoUIDFinal/imagini/Boss/BaileyWaiting.png"
boss.bg1="/org/example/ProgettoUIDFinal/imagini/Boss/BossBackground1.png"

boss.name2="Artorias"
boss.hp2=600
boss.atk2=55
boss.def2=40
boss.vel2=70
boss.sprite2="/org/example/ProgettoUIDFinal/images/bossSprite.png"
boss.bg2="/org/example/ProgettoUIDFinal/imagini/Boss/BossBackground.jpg"

image.victory=/org/example/ProgettoUIDFinal/images/victory.png
image.defeat=/org/example/ProgettoUIDFinal/images/defeat.png