boss.name=Nergigante

boss.hp=100
boss.atk=20
boss.def=15
boss.vel=50

boss.sprite=/org/example/ProgettoUIDFinal/images/bossSprite.png

image.victory=/org/example/ProgettoUIDFinal/images/victory.png
image.defeat=/org/example/ProgettoUIDFinal/images/defeat.png