malebrown="imagini/hats/witch.png"
maleblonde="imagini/hats/helmet.png"
maleblack="imagini/hats/crown.png"
girlbrown="imagini/hats/chef.png"
girlblonde="imagini/hats/bluebert.png"
girlblack="imagini/hats/santa.png"
hatsunemiku="imagini/hats/artist.png"
girlawakened="imagini/hats/graduation.png"
boyawakened="imagini/hats/pirate.png"


player.name=Monogat.ari

player.xp=0.5
player.atk=0.5
player.def=0.1
player.vel=0.8

profile.pic1="images/chr_icon_1052.png"
profile.pic2="images/chr_icon_1007.png"
profile.pic3="images/chr_icon_1025.png"
profile.pic4="images/chr_icon_1053.png"