malebrown="imagini/hats/witch.png"
maleblonde="imagini/hats/helmet.png"
maleblack="imagini/hats/crown.png"
girlbrown="imagini/hats/chef.png"
girlblonde="imagini/hats/bluebert.png"
girlblack="imagini/hats/santa.png"
hatsunemiku="imagini/hats/artist.png"
girlawakened="imagini/hats/graduation.png"
boyawakened="imagini/hats/pirate.png"