malebrown="/org/example/ProgettoUIDFinal/imagini/hats/witch.png"
maleblonde="/org/example/ProgettoUIDFinal/imagini/hats/helmet.png"
maleblack="/org/example/ProgettoUIDFinal/imagini/hats/crown.png"
girlbrown="/org/example/ProgettoUIDFinal/imagini/hats/chef.png"
girlblonde="/org/example/ProgettoUIDFinal/imagini/hats/bluebert.png"
girlblack="/org/example/ProgettoUIDFinal/imagini/hats/santa.png"
hatsunemiku="/org/example/ProgettoUIDFinal/imagini/hats/artist.png"
girlawakened="/org/example/ProgettoUIDFinal/imagini/hats/graduation.png"
boyawakened="/org/example/ProgettoUIDFinal/imagini/hats/pirate.png"


player.name=Monogat.ari

player.xp=1
player.atk=0.2
player.def=0.1
player.vel=0.8

profile.pic1="/org/example/ProgettoUIDFinal/images/chr_icon_1052.png"
profile.pic2="/org/example/ProgettoUIDFinal/images/chr_icon_1007.png"
profile.pic3="/org/example/ProgettoUIDFinal/images/chr_icon_1025.png"
profile.pic4="/org/example/ProgettoUIDFinal/images/chr_icon_1053.png"