armor.dres1="imagini/armors/witch.png"
armor.dres2="imagini/armors/helmet.png"
armor.dres3="imagini/armors/crown.png"
armor.dres4="imagini/armors/chef.png"
armor.dres5="imagini/armors/bluebert.png"
armor.dres6="imagini/armors/santa.png"
armor.dres7="imagini/armors/artist.png"
armor.dres8="imagini/armors/graduation.png"
armor.dres9="imagini/armors/pirate.png"

hat.cap1="imagini/hats/witch.png"
hat.cap2="imagini/hats/helmet.png"
hat.cap3="imagini/hats/crown.png"
hat.cap4="imagini/hats/chef.png"
hat.cap5="imagini/hats/bluebert.png"
hat.cap6="imagini/hats/santa.png"
hat.cap7="imagini/hats/artist.png"
hat.cap8="imagini/hats/graduation.png"
hat.cap9="imagini/hats/pirate.png"

# === SFONDI (Backgrounds) ===
# L'ID deve coincidere con il nome del bottone nel FXML (Btn1 -> btn1)
background.btn1="imagini/Backgrounds/dungeon.jpg"
background.btn2="imagini/Backgrounds/space.jpg"
background.btn3="imagini/Backgrounds/standard.jpg"
background.btn4="imagini/Backgrounds/yokai.jpg"
background.btn5="imagini/Backgrounds/sunny.jpg"
background.btn6="imagini/Backgrounds/forest.jpg"
background.btn7="imagini/Backgrounds/autumn.jpg"
background.btn8="imagini/Backgrounds/canyon.jpg"
background.btn9="imagini/Backgrounds/city.jpg"
