# === ARMATURE (Armor) ===
armor.dres1="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-armor-1.png"
icon.dres1="/org/example/ProgettoUIDFinal/imagini/armors/Cuoio.png"
name.dres1="Armatura di Cuoio"

armor.dres2="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-armor-2.png"
icon.dres2="/org/example/ProgettoUIDFinal/imagini/armors/iron.png"
name.dres2="Armatura di Ferro"

armor.dres3="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-armor-3.png"
icon.dres3="/org/example/ProgettoUIDFinal/imagini/armors/golden.png"
name.dres3="Armatura d'Oro"

armor.dres4="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-armor-4.png"
icon.dres4="/org/example/ProgettoUIDFinal/imagini/armors/dark.png"
name.dres4="Armatura Oscura"

# === CAPPELLI (Hats) ===
hat.cap1="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-witchhat-1.png"
icon.cap1="/org/example/ProgettoUIDFinal/imagini/Hats/witch.png"
name.cap1="Cappello da Strega"

hat.cap2="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-helmet-iron.png"
icon.cap2="/org/example/ProgettoUIDFinal/imagini/Hats/iron-helmet.png"
name.cap2="Elmetto di Ferro"

hat.cap3="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-crown.png"
icon.cap3="/org/example/ProgettoUIDFinal/imagini/Hats/crown.png"
name.cap3="Corona"

hat.cap4="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-helmet-gold.png"
icon.cap4="/org/example/ProgettoUIDFinal/imagini/Hats/gold-helmet.png"
name.cap4="Elmetto d'Oro"

hat.cap5="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hood.png"
icon.cap5="/org/example/ProgettoUIDFinal/imagini/Hats/hood.png"
name.cap5="Cappuccio"

#===CAPELLI(Hair)===
hair.har1="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hair-1.png"
icon.har1="/org/example/ProgettoUIDFinal/imagini/hair/hair-brown.png"
name.har1="Coda Castana"

hair.har2="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hair-2.png"
icon.har2="/org/example/ProgettoUIDFinal/imagini/hair/hair-light-brown.png"
name.har2="Coda Castano Chiaro"

hair.har3="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hair-3.png"
icon.har3="/org/example/ProgettoUIDFinal/imagini/hair/hair-hatsune-miku.png"
name.har3="Hatsune Miku"

hair.har4="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hair-4.png"
icon.har4="/org/example/ProgettoUIDFinal/imagini/hair/hair-hatsune-miku-pink.png"
name.har4="Sakura Miku"

hair.har5="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hair-5.png"
icon.har5="/org/example/ProgettoUIDFinal/imagini/hair/hair-black.png"
name.har5="Lunghi Corvini"

hair.har6="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hair-6.png"
icon.har6="/org/example/ProgettoUIDFinal/imagini/hair/hair-2b.png"
name.har6="Caschetto Corto"

# === SFONDI (Backgrounds) ===
background.btn1="/org/example/ProgettoUIDFinal/imagini/Backgrounds/dungeon.jpg"
background.btn2="/org/example/ProgettoUIDFinal/imagini/Backgrounds/space.jpg"
background.btn3="/org/example/ProgettoUIDFinal/imagini/Backgrounds/standard.jpg"
background.btn4="/org/example/ProgettoUIDFinal/imagini/Backgrounds/yokai.jpg"
background.btn5="/org/example/ProgettoUIDFinal/imagini/Backgrounds/sunny.jpg"
background.btn6="/org/example/ProgettoUIDFinal/imagini/Backgrounds/forest.jpg"
background.btn7="/org/example/ProgettoUIDFinal/imagini/Backgrounds/autumn.jpg"
background.btn8="/org/example/ProgettoUIDFinal/imagini/Backgrounds/canyon.jpg"
background.btn9="/org/example/ProgettoUIDFinal/imagini/Backgrounds/city.jpg"

# === Weapons ===
sword.sword1=""
icon.sword1="/org/example/ProgettoUIDFinal/imagini/weapons/sword-lv-1.png"
name.sword1="Spada lv1"
atk.sword1=0

sword.sword2="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-sword-2.png"
icon.sword2="/org/example/ProgettoUIDFinal/imagini/weapons/sword-lv-2.png"
name.sword2="Spada lv2"
atk.sword2=2

sword.sword3="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-sword-3.png"
icon.sword3="/org/example/ProgettoUIDFinal/imagini/weapons/sword-lv-3.png"
name.sword3="Spada lv3"
atk.sword3=4

sword.sword4="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-sword-4.png"
icon.sword4="/org/example/ProgettoUIDFinal/imagini/weapons/sword-lv-4.png"
name.sword4="Spada lv4"
atk.sword4=6

shield.shield1=""
icon.shield1="/org/example/ProgettoUIDFinal/imagini/weapons/shield-lv-1.png"
name.shield1="Scudo lv1"
def.shield1=0

shield.shield2="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-shield-2.png"
icon.shield2="/org/example/ProgettoUIDFinal/imagini/weapons/shield-lv-2.png"
name.shield2="Scudo lv2"
def.shield2=2

shield.shield3="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-shield-3.png"
icon.shield3="/org/example/ProgettoUIDFinal/imagini/weapons/shield-lv-3.png"
name.shield3="Scudo lv3"
def.shield3=4

shield.shield4="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-shield-4.png"
icon.shield4="/org/example/ProgettoUIDFinal/imagini/weapons/shield-lv-4.png"
name.shield4="Scudo lv4"
def.shield4=6



