boss.name0="Nergigante"
boss.hp0=60
boss.atk0=15
boss.def0=5
boss.vel0=8
boss.sprite0="/org/example/ProgettoUIDFinal/imagini/Boss/Sprite-boss-nergigante.png"
boss.bg0="/org/example/ProgettoUIDFinal/imagini/Boss/BossBackground0.png"
boss.arena0="/org/example/ProgettoUIDFinal/imagini/Boss/BossArena0.png"
boss.rlevel0="10"
boss.music0="Battle_theme.mp3"

boss.name1="Maga"
boss.hp1=150
boss.atk1=40
boss.def1=25
boss.vel1=25
boss.sprite1="/org/example/ProgettoUIDFinal/imagini/Boss/Sprite-boss-mage.png"
boss.bg1="/org/example/ProgettoUIDFinal/imagini/Boss/BossBackground1.png"
boss.arena1="/org/example/ProgettoUIDFinal/imagini/Boss/BossArena1.png"
boss.rlevel1="30"
boss.music1="mage_theme.mp3"

boss.name2="Artorias"
boss.hp2=300
boss.atk2=75
boss.def2=55
boss.vel2=55
boss.sprite2="/org/example/ProgettoUIDFinal/imagini/Boss/Sprite-boss-knight.png"
boss.bg2="/org/example/ProgettoUIDFinal/imagini/Boss/BossBackground2.jpg"
boss.arena2="/org/example/ProgettoUIDFinal/imagini/Boss/BossArena2.png"
boss.rlevel2="60"
boss.music2="ninja_theme.mp3"

image.victory=/org/example/ProgettoUIDFinal/images/victory.png
image.defeat=/org/example/ProgettoUIDFinal/images/defeat.png