profile.pic1="/org/example/ProgettoUIDFinal/imagini/chr_icon_1052.png"
profile.pic2="/org/example/ProgettoUIDFinal/imagini/chr_icon_1007.png"
profile.pic3="/org/example/ProgettoUIDFinal/imagini/chr_icon_1025.png"
profile.pic4="/org/example/ProgettoUIDFinal/imagini/chr_icon_1053.png"

# === MODELLO ATTUALE ===
# NOTA: Usa / (slash), NON \ (backslash)
char.model="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-base.png"

char.avatar="org/example/ProgettoUIDFinal/imagini/profile/Icons/chr_icon_1052.png"
char.banner="org/example/ProgettoUIDFinal/imagini/profile/banners/Banner1.png"

char.hair=""
char.hat=""
char.dres=""
char.sword="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-sword-1.png"
char.shield="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-shield-1.png"

icon.hair="/org/example/ProgettoUIDFinal/imagini/Icon-hair.png"
icon.hat="/org/example/ProgettoUIDFinal/imagini/Icon-helmet.png"
icon.dres="/org/example/ProgettoUIDFinal/imagini/Icon-armor.png"
icon.sword="org/example/ProgettoUIDFinal/imagini/weapons/sword-lv-1.png"
icon.shield="org/example/ProgettoUIDFinal/imagini/weapons/shield-lv-1.png"

name.hair="Nessuna acconciatura"
name.hat="Nessun cappello"
name.dres="Nessuna armatura"
name.sword="Spada di legno"
name.shield="Scudo di legno"