character.properties
malebrown="/org/example/ProgettoUIDFinal/imagini/hats/witch.png"
maleblonde="/org/example/ProgettoUIDFinal/imagini/hats/helmet.png"
maleblack="/org/example/ProgettoUIDFinal/imagini/hats/crown.png"
girlbrown="/org/example/ProgettoUIDFinal/imagini/hats/chef.png"
girlblonde="/org/example/ProgettoUIDFinal/imagini/hats/bluebert.png"
girlblack="/org/example/ProgettoUIDFinal/imagini/hats/santa.png"
hatsunemiku="/org/example/ProgettoUIDFinal/imagini/hats/artist.png"
girlawakened="/org/example/ProgettoUIDFinal/imagini/hats/graduation.png"
boyawakened="/org/example/ProgettoUIDFinal/imagini/hats/pirate.png"

profile.pic1="/org/example/ProgettoUIDFinal/imagini/chr_icon_1052.png"
profile.pic2="/org/example/ProgettoUIDFinal/imagini/chr_icon_1007.png"
profile.pic3="/org/example/ProgettoUIDFinal/imagini/chr_icon_1025.png"
profile.pic4="/org/example/ProgettoUIDFinal/imagini/chr_icon_1053.png"

# === MODELLO ATTUALE ===
# NOTA: Usa / (slash), NON \ (backslash)
char.model="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-base.png"
char.sword="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-sword-1.png"
char.shield="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-shield-1.png"

icon.hair="/org/example/ProgettoUIDFinal/imagini/Icon-hair.png"
icon.hat="/org/example/ProgettoUIDFinal/imagini/Icon-helmet.png"
icon.dres="/org/example/ProgettoUIDFinal/imagini/Icon-armor.png"
icon.sword="/org/example/ProgettoUIDFinal/imagini/Icon-sword.png"
icon.shield="/org/example/ProgettoUIDFinal/imagini/Icon-shield.png"
