# === ARMATURE (Armor) ===
male.dres1="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-armor-1.png"
female.dres1="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-armor-1.png"
icon.dres1="/org/example/ProgettoUIDFinal/imagini/armors/Cuoio.png"
name.dres1="Armatura di Cuoio"

male.dres2="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-armor-2.png"
female.dres2="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-armor-2.png"
icon.dres2="/org/example/ProgettoUIDFinal/imagini/armors/iron.png"
name.dres2="Armatura di Ferro"

male.dres3="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-armor-3.png"
female.dres3="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-armor-3.png"
icon.dres3="/org/example/ProgettoUIDFinal/imagini/armors/golden.png"
name.dres3="Armatura d'Oro"

male.dres4="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-armor-4.png"
female.dres4="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-armor-4.png"
icon.dres4="/org/example/ProgettoUIDFinal/imagini/armors/dark.png"
name.dres4="Armatura Oscura"

male.dres5="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-armor-5.png"
female.dres5="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-armor-5.png"
icon.dres5="/org/example/ProgettoUIDFinal/imagini/armors/snow.png"
name.dres5="Armatura Dei Ghiacci"

# === CAPPELLI (Hats) ===
male.cap1="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-witchhat.png"
female.cap1="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-witchhat.png"
icon.cap1="/org/example/ProgettoUIDFinal/imagini/Hats/witch.png"
name.cap1="Cappello da Strega"

male.cap2="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-helmet-iron.png"
female.cap2="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-helmet-iron.png"
icon.cap2="/org/example/ProgettoUIDFinal/imagini/Hats/iron-helmet.png"
name.cap2="Elmetto di Ferro"

male.cap3="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-crown.png"
female.cap3="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-crown.png"
icon.cap3="/org/example/ProgettoUIDFinal/imagini/Hats/crown.png"
name.cap3="Corona"

male.cap4="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-helmet-gold.png"
female.cap4="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-helmet-gold.png"
icon.cap4="/org/example/ProgettoUIDFinal/imagini/Hats/gold-helmet.png"
name.cap4="Elmetto d'Oro"

male.cap5="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-hood.png"
female.cap5="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hood.png"
icon.cap5="/org/example/ProgettoUIDFinal/imagini/Hats/hood.png"
name.cap5="Cappuccio"

#===CAPELLI(Hair)===
male.har1="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-hair-1.png"
female.har1="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hair-1.png"
icon.har1="/org/example/ProgettoUIDFinal/imagini/hair/hair-brown.png"
name.har1="Coda Castana"

male.har2="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-hair-2.png"
female.har2="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hair-2.png"
icon.har2="/org/example/ProgettoUIDFinal/imagini/hair/hair-black.png"
name.har2="Lunghi Lisci"

male.har3="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-hair-3.png"
female.har3="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hair-3.png"
icon.har3="/org/example/ProgettoUIDFinal/imagini/hair/hair-2b.png"
name.har3="Caschetto"

male.har4="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-hair-4.png"
female.har4="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hair-4.png"
icon.har4="/org/example/ProgettoUIDFinal/imagini/hair/hair-hatsune-miku.png"
name.har4="Hatsune Miku"

male.har5="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-hair-5.png"
female.har5="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hair-5.png"
icon.har5="/org/example/ProgettoUIDFinal/imagini/hair/hair-curl-brown.png"
name.har5="Riccioli"

male.har6="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-hair-6.png"
female.har6="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hair-6.png"
icon.har6="/org/example/ProgettoUIDFinal/imagini/hair/hair-middle-part.png"
name.har6="Riga Centrale"

male.har7="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-hair-7.png"
female.har7="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hair-7.png"
icon.har7="/org/example/ProgettoUIDFinal/imagini/hair/hair-short-black.png"
name.har7="Taglio Corto"

male.har8="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-hair-8.png"
female.har8="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-hair-8.png"
icon.har8="/org/example/ProgettoUIDFinal/imagini/hair/hair-goku.png"
name.har8="Goku"

# === SFONDI (Backgrounds) ===
background.btn1="/org/example/ProgettoUIDFinal/imagini/Backgrounds/dungeon.png"
background.layer1="/org/example/ProgettoUIDFinal/imagini/Backgrounds/layers/dungeon.png"
background.btn2="/org/example/ProgettoUIDFinal/imagini/Backgrounds/space.png"
background.layer2="/org/example/ProgettoUIDFinal/imagini/Backgrounds/layers/space.png"
background.btn3="/org/example/ProgettoUIDFinal/imagini/Backgrounds/castle.png"
background.layer3="/org/example/ProgettoUIDFinal/imagini/Backgrounds/layers/castle.png"
background.btn4="/org/example/ProgettoUIDFinal/imagini/Backgrounds/japan.png"
background.layer4="/org/example/ProgettoUIDFinal/imagini/Backgrounds/layers/japan.png"
background.btn5="/org/example/ProgettoUIDFinal/imagini/Backgrounds/sunny.png"
background.layer5="/org/example/ProgettoUIDFinal/imagini/Backgrounds/layers/sunny.png"
background.btn6="/org/example/ProgettoUIDFinal/imagini/Backgrounds/forest.png"
background.layer6="/org/example/ProgettoUIDFinal/imagini/Backgrounds/layers/forest.png"
background.btn7="/org/example/ProgettoUIDFinal/imagini/Backgrounds/autumn.png"
background.layer7="/org/example/ProgettoUIDFinal/imagini/Backgrounds/layers/autumn.png"
background.btn8="/org/example/ProgettoUIDFinal/imagini/Backgrounds/canyon.png"
background.layer8="/org/example/ProgettoUIDFinal/imagini/Backgrounds/layers/canyon.png"
background.btn9="/org/example/ProgettoUIDFinal/imagini/Backgrounds/snow.png"
background.layer9="/org/example/ProgettoUIDFinal/imagini/Backgrounds/layers/snow.png"

# === Weapons ===
male.sword0="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-sword-1.png"
female.sword0="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-sword-1.png"
icon.sword0="/org/example/ProgettoUIDFinal/imagini/weapons/sword-lv-1.png"
name.sword0="Spada di Legno"

male.sword1="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-sword-2.png"
female.sword1="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-sword-2.png"
icon.sword1="/org/example/ProgettoUIDFinal/imagini/weapons/sword-lv-2.png"
name.sword1="Spada Lv 1"

male.sword2="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-sword-3.png"
female.sword2="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-sword-3.png"
icon.sword2="/org/example/ProgettoUIDFinal/imagini/weapons/sword-lv-3.png"
name.sword2="Spada Lv 2"

male.sword3="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-sword-4.png"
female.sword3="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-sword-4.png"
icon.sword3="/org/example/ProgettoUIDFinal/imagini/weapons/sword-lv-4.png"
name.sword3="Spada Lv 3"

male.shield0="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-shield-1.png"
female.shield0="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-shield-1.png"
icon.shield0="/org/example/ProgettoUIDFinal/imagini/weapons/shield-lv-1.png"
name.shield0="Scudo di legno"

male.shield1="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-shield-2.png"
female.shield1="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-shield-2.png"
icon.shield1="/org/example/ProgettoUIDFinal/imagini/weapons/shield-lv-2.png"
name.shield1="Scudo Lv1"

male.shield2="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-shield-3.png"
female.shield2="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-shield-3.png"
icon.shield2="/org/example/ProgettoUIDFinal/imagini/weapons/shield-lv-3.png"
name.shield2="Scudo Lv 2"

male.shield3="/org/example/ProgettoUIDFinal/imagini/male sprites/Sprite-male-shield-4.png"
female.shield3="/org/example/ProgettoUIDFinal/imagini/female sprites/Sprite-female-shield-4.png"
icon.shield3="/org/example/ProgettoUIDFinal/imagini/weapons/shield-lv-4.png"
name.shield3="Scudo Lv 3"

male.boots0=""
female.boots0=""
icon.boots0="/org/example/ProgettoUIDFinal/imagini/weapons/boots-lv-2.png"
name.boots0="Stivali"

male.boots1=""
female.boots1=""
icon.boots1="/org/example/ProgettoUIDFinal/imagini/weapons/boots-lv-2.png"
name.boots1="Stivali Lv1"

male.boots2=""
female.boots2=""
icon.boots2="/org/example/ProgettoUIDFinal/imagini/weapons/boots-lv-3.png"
name.boots2="Stivali Lv2"

male.boots3=""
female.boots3=""
icon.boots3="/org/example/ProgettoUIDFinal/imagini/weapons/boots-lv-4.png"
name.boots3="Stivali Lv3"







